# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='logo_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
